# Generated by Django 3.0.8 on 2020-09-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='account',
            name='picture',
        ),
    ]
