# Generated by Django 3.0.8 on 2020-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200916_0444'),
        ('accounts', '0003_auto_20200919_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to='products.Product'),
        ),
    ]
