# Generated by Django 3.0.8 on 2020-10-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='favorite',
        ),
    ]
